scan report v1
armosec/cluster-container-scanner-api pull request #1
Opened 2022-06-20 13:28 UTC by avrahams

Create ScanResultReportV1 with ready to use Vulnerabilities and report summery

2022-06-21 09:41 UTC, LiorAlafiArmo commented on containerscan/rawdatastrucutres.go
> +	CustomerGUID    string                               `json:"customerGUID"`
לדעתי מיותר, השדה הזה גם ככה נמצא בdesignators

2022-06-21 09:43 UTC, LiorAlafiArmo commented on containerscan/rawdatastrucutres.go
> +	PartNum         int                                  `json:"partNum"`
נא להכניס/למצוא pagination structure בתוך armotypes ולא כindividual fields, מחר אם נרצה להגדיל את זה הקונטקסט של השדות יהיה מפוזר...

2022-06-21 09:45 UTC, LiorAlafiArmo commented on containerscan/datastructuresmethods.go
> +func (scanresult *ScanResultReportV1) Validate() bool {
אולי כדאי לעטוף בinterface ולכתוב validator ו isRCE לאינטרפייס וזהו? (לא חובה-הצעה.)

2022-06-21 18:24 UTC, avrahams commented on containerscan/rawdatastrucutres.go
> +	PartNum         int                                  `json:"partNum"`
@LiorAlafiArmo 
I see that PaginationMarks is in opa-utils
https://github.com/armosec/opa-utils/blob/master/reporthandling/v2/datastructures.go#L13
Does it make sene to create a dependency from cluster-container-scanner-api to opa-utils or PaginationMarks struct should move to another package?

2022-06-21 18:30 UTC, avrahams commented on containerscan/rawdatastrucutres.go
> +	CustomerGUID    string                               `json:"customerGUID"`
This is the same implementation as ScanReportV0
It is used in `(scanresult *ScanResultReport) GetDesignatorsNContext() (*armotypes.PortalDesignator, []armotypes.ArmoContext) {`

2022-06-22 13:00 UTC, Bezbran requested changes

2022-06-22 13:00 UTC, Bezbran commented on containerscan/datastructuresmethods.go
> +func (scanresult *ScanResultReportV1) GetDesignatorsNContext() (*armotypes.PortalDesignator, []armotypes.ArmoContext) {
add unitests

2022-06-22 13:00 UTC, Bezbran commented on containerscan/rawdatastrucutres.go
> +	Summery         *CommonContainerScanSummaryResult    `json:"summery,omitempty"`
Summary

2022-06-22 13:00 UTC, Bezbran commented on containerscan/rawdatastrucutres.go
> +	CustomerGUID    string                               `json:"customerGUID"`
In addition - for registry scan we have no WLID nor container name

2022-06-22 13:00 UTC, Bezbran commented on containerscan/rawdatastrucutres.go
> +	CustomerGUID    string                               `json:"customerGUID"`
we just need to see if UI is using this field - if so we should tell them to stop using it or calculate it only upon Elastic insertion

2022-06-26 18:08 UTC, avrahams commented on containerscan/datastructuresmethods.go
> +func (scanresult *ScanResultReportV1) Validate() bool {
Bez input was not to put effort in V0 scan reports

2022-06-26 18:09 UTC, avrahams commented on containerscan/rawdatastrucutres.go
> +	CustomerGUID    string                               `json:"customerGUID"`
done

2022-06-29 08:22 UTC, Bezbran approved these changes

2022-06-29 08:22 UTC, merged