eslayer extention
armosec/cluster-container-scanner-api pull request #2
Opened 2022-08-03 11:20 UTC by OleksiiHahren

2022-08-03 11:44 UTC, Bezbran requested changes

2022-08-03 11:44 UTC, Bezbran commented on containerscan/commondatastructures.go
> +	CreatedTime *date.Date
Please use time.Time

2022-08-03 11:57 UTC, Bezbran approved these changes

2022-08-03 12:03 UTC, merged

2022-08-04 05:46 UTC, cigra commented on containerscan/commondatastructures.go
> +	CreatedBy   string
Add json annotation here please